# -*- mode: ruby -*-
# vi: set ft=ruby :

################################################################
################################################################
####### VM configuration. DON'T FORGET TO CHANGE THESE  ########
################################################################
################################################################

http_proxy = 'http://172.28.40.9:3128'
bonfire_vm_basebox = 'ubuntu/trusty64'
bonfire_vm_ram = '8192'
bonfire_vm_cpus = '2'
bonfire_vm_private_network_ip = '10.1.1.40'
bonfire_vm_hostname = 'bonfire'
################################################################


Vagrant.configure(2) do |config|

	config.ssh.username = 'vagrant'
	config.ssh.password = 'vagrant'

    if !http_proxy.eql?''
        if Vagrant.has_plugin?('vagrant-proxyconf')
            config.proxy.http = http_proxy
            config.proxy.https = http_proxy
            config.proxy.no_proxy = 'localhost,127.0.0.1,' + bonfire_vm_private_network_ip
        else
            abort("vagrant-proxyconf plugin missing. Exiting.")
        end
    end

    config.ssh.shell = 'bash -c "BASH_ENV=/etc/profile exec bash"'


    uid_bonfire = ENV.has_key?('VM_UID') ? '_' + ENV['VM_UID'].split('-')[0] : '_' + bonfire_vm_private_network_ip

    config.vm.define 'bonfire_ubuntu_box' do |machine|

	
        machine.vm.box = bonfire_vm_basebox
        puts "Bringing up VM with IP: " + bonfire_vm_private_network_ip

        machine.vm.box = bonfire_vm_basebox
        machine.vm.host_name = bonfire_vm_hostname + '.' + bonfire_vm_hostname
        machine.vm.network :private_network, ip: bonfire_vm_private_network_ip

        machine.vm.provider :virtualbox do |vb|
            # Display the VirtualBox GUI when booting the machine
            #vb.gui = true

            # Customize the amount of memory on the VM:
            vb.memory = bonfire_vm_ram
            vb.cpus = bonfire_vm_cpus
            # change the network card hardware for better performance
            vb.customize ["modifyvm", :id, "--nictype1", "virtio" ]
            vb.customize ["modifyvm", :id, "--nictype2", "virtio" ]
        end

    end

    config.vm.provision :shell, privileged: true, :path => 'provisioning/provision.sh'
    config.vm.provision :shell, privileged: true, :path => 'provisioning/java-setup.sh'
    config.vm.provision :shell, privileged: true, :path => 'provisioning/odl-setup.sh'
    config.vm.provision :shell, privileged: true, :path => 'provisioning/settings-xml-setup.sh'

end
